check50: 
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !exclude Makefile
    - !exclude application.py
    - !exclude compare
    - !require helpers.py
    - !require templates/index.html

submit50:
  files: *check50_files
