submit50:
  style: false
  remote:
    message: "Go to your dashboard at https://cs50.cs.yale.edu/20su/dashboard to see your submission.  (It may take a few minutes for this submission to appear.)"
    callback: https://cs50.cs.yale.edu/20su/api/submit50

