check50: 
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !exclude requirements.txt
    - !require helpers.py
    - !require templates/index.html
    - !require templates/matrix.html
submit50:
  files: *check50_files
