check50: 
  files: &check50_files
    - !exclude "*.pyc"
    - !exclude __pycache__
    - !exclude ".*"
    - !require application.py
    - !require mashup.db
    - !require static/scripts.js

submit50:
  files: *check50_files
