check50: 
  files: &check50_files
    - !exclude "*"
    - !include "*.c"
    - !include "*.h"
    - !require dictionary.c
    - !require dictionary.h
    - !require Makefile

submit50:
  files: *check50_files
