submit50:
  style: false
  files: &submit50_files
    - !exclude "*"
    - !include "*.sql"
    - !require 1.sql
    - !require 2.sql
    - !require 3.sql
    - !require 4.sql
    - !require 5.sql
    - !require 6.sql
    - !require 7.sql
    - !require 8.sql
    - !require 9.sql
    - !require 10.sql
    - !require 11.sql
    - !require 12.sql
    - !require 13.sql
  remote:
    message: "Go to your dashboard at https://cs50.cs.yale.edu/19fa/dash50 to see your score and access your check50 and style50 output.  (It may take a few minutes for this submission to appear.)"
    callback: https://cs50.cs.yale.edu/19fa/api/submit50
