check50:
  files: &check50_files
  - !exclude "*"
  - !include "*.sql"
  - !require "1.sql"
  - !require "2.sql"
  - !require "3.sql"
  - !require "4.sql"
  - !require "5.sql"

submit50:
  files: *check50_files
  style: false
